#!/usr/bin/env python3
"""
extract_flat_pdf_ground_truth.py

Bootstrap ground truth for flat PDFs from heuristic backend output.

Flat PDFs have NO AcroForm widgets, so widget-based extraction
(extract_ground_truth.py) doesn't apply. Instead we:

1. Run a heuristic backend on the flat PDF
2. Save its output to benchmarks/ground_truth_flat/<pdf_id>.draft.json
3. Human reviews the draft (visual overlay), marks corrections
4. Promote draft → benchmarks/ground_truth_flat/<pdf_id>.json

The draft file uses the same schema as benchmarks/ground_truth/<pdf_id>.json
(generated by extract_ground_truth.py) so the existing run_benchmark.py
and renderers work unchanged.

Initial bootstrap policy: use heuristic_lab_v2 output as draft. v2 is
optimistic (catches char-box rows that v1 misses), so the draft will
include more candidate fields than v1 would produce. Human review then
keeps/removes/adjusts as needed.

Usage:
  python scripts/extract_flat_pdf_ground_truth.py --pdf <pdf_id> [--backend heuristic_lab_v2]
  python scripts/extract_flat_pdf_ground_truth.py --pdf marriage_license --promote

Guardrails:
- READ-ONLY for source PDFs
- All writes confined to benchmarks/ground_truth_flat/
- --dry-run reports what would be done
- --promote requires a .draft.json to exist
- Will not overwrite existing .json without --force
"""

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from backend_registry import get_backend, list_backends


ROOT = Path(__file__).resolve().parent.parent
FLAT_MANIFEST = ROOT / "samples" / "flat" / "manifest.json"
GT_FLAT_DIR = ROOT / "benchmarks" / "ground_truth_flat"


def assert_safe_output_path(path: Path) -> None:
    resolved = path.resolve()
    expected = GT_FLAT_DIR.resolve()
    try:
        resolved.relative_to(expected)
    except ValueError:
        raise RuntimeError(f"Refused to write outside {expected}: {resolved}")


def find_pdf_path(pdf_id: str) -> Path | None:
    """Look up PDF by id in flat manifest, or by direct path search."""
    if FLAT_MANIFEST.exists():
        manifest = json.loads(FLAT_MANIFEST.read_text())
        for entry in manifest:
            if entry.get("id") == pdf_id:
                return ROOT / entry["filename"]

    # Fallback: search samples/flat/ for PDFs matching the pdf_id
    flat_root = ROOT / "samples" / "flat"
    if flat_root.exists():
        for pdf_path in flat_root.rglob("*.pdf"):
            stem = pdf_path.stem.lower()
            if pdf_id.lower() == stem or pdf_id.lower() in stem:
                return pdf_path

    return None


def bootstrap_draft(pdf_path: Path, pdf_id: str, backend_name: str, dry_run: bool) -> dict:
    """Run backend, return draft GT structure."""
    backend_fn = get_backend(backend_name)
    detected = backend_fn(pdf_path)

    # Try to get page count from the PDF
    try:
        import pypdfium2 as pdfium
        with pdfium.PdfDocument(str(pdf_path)) as doc:
            page_count = len(doc)
    except Exception:
        page_count = max((f.get("page", 1) for f in detected), default=1)

    # Reshape detected -> GT schema (same as extract_ground_truth.py output)
    gt_fields = []
    for i, f in enumerate(detected, start=1):
        gt_fields.append({
            "id": f"g{i}",                     # ground truth ids prefixed 'g' to distinguish
            "page": f["page"],
            "type": f["type"],
            "bbox": f["bbox"],
            "label": f.get("label"),
            "_source_detection_id": f["id"],   # trace back to source
            "_reviewer_status": "draft",        # human edits this: keep / remove / adjust
        })

    return {
        "schema_version": "1.0",
        "pdf_id": pdf_id,
        "pdf": pdf_path.name,
        "page_count": page_count,
        "extraction_method": "flat_pdf_bootstrap",
        "bootstrap_backend": backend_name,
        "bootstrap_timestamp": datetime.now().isoformat(),
        "review_status": "draft",
        "needs_review": True,
        "fields": gt_fields,
    }


def promote_draft(pdf_id: str, force: bool) -> int:
    draft_path = GT_FLAT_DIR / f"{pdf_id}.draft.json"
    final_path = GT_FLAT_DIR / f"{pdf_id}.json"

    if not draft_path.exists():
        print(f"ERROR: no draft at {draft_path}", file=sys.stderr)
        return 2
    if final_path.exists() and not force:
        print(f"ERROR: {final_path} exists. Use --force to overwrite.", file=sys.stderr)
        return 3

    draft = json.loads(draft_path.read_text())

    # Strip reviewer status markers; verify all fields have been reviewed
    unreviewed = [f for f in draft["fields"]
                  if f.get("_reviewer_status") not in ("kept", "adjusted")]
    if unreviewed and not force:
        print(f"ERROR: {len(unreviewed)} fields still marked '_reviewer_status: draft'",
              file=sys.stderr)
        print("Review all fields (mark 'kept' or 'adjusted' or remove from list), then promote.",
              file=sys.stderr)
        print("Or use --force to promote anyway (NOT recommended).", file=sys.stderr)
        return 4

    promoted = {
        "schema_version": draft.get("schema_version", "1.0"),
        "pdf_id": draft["pdf_id"],
        "pdf": draft["pdf"],
        "page_count": draft["page_count"],
        "extraction_method": draft.get("extraction_method", "flat_pdf_bootstrap"),
        "review_status": "human_reviewed",
        "promoted_timestamp": datetime.now().isoformat(),
        "bootstrap_backend": draft.get("bootstrap_backend"),
        "fields": [
            {k: v for k, v in f.items()
             if k not in ("_source_detection_id", "_reviewer_status")}
            for f in draft["fields"]
        ],
    }

    assert_safe_output_path(final_path)
    final_path.write_text(json.dumps(promoted, indent=2))
    print(f"Promoted: {final_path.relative_to(ROOT)}")
    print(f"  Fields: {len(promoted['fields'])}")
    return 0


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--pdf", required=True, help="PDF id (e.g. 'marriage_license')")
    parser.add_argument("--backend", default="heuristic_lab_v2",
                        choices=list_backends(),
                        help="Backend to bootstrap from")
    parser.add_argument("--promote", action="store_true",
                        help="Promote existing draft to final GT")
    parser.add_argument("--force", action="store_true",
                        help="Overwrite existing final GT during promote")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    if args.promote:
        sys.exit(promote_draft(args.pdf, args.force))

    pdf_path = find_pdf_path(args.pdf)
    if pdf_path is None:
        print(f"ERROR: PDF id '{args.pdf}' not found", file=sys.stderr)
        print(f"  Searched: {FLAT_MANIFEST} and samples/flat/", file=sys.stderr)
        sys.exit(1)
    if not pdf_path.exists():
        print(f"ERROR: PDF file does not exist: {pdf_path}", file=sys.stderr)
        sys.exit(1)

    print(f"{'='*72}")
    print(f"extract_flat_pdf_ground_truth.py")
    if args.dry_run:
        print("MODE: DRY RUN")
    print(f"PDF id: {args.pdf}")
    print(f"PDF path: {pdf_path}")
    print(f"Backend: {args.backend}")
    print(f"{'='*72}")

    draft = bootstrap_draft(pdf_path, args.pdf, args.backend, args.dry_run)

    print(f"Bootstrapped {len(draft['fields'])} candidate fields")
    type_counts = {}
    for f in draft["fields"]:
        type_counts[f["type"]] = type_counts.get(f["type"], 0) + 1
    for t, n in sorted(type_counts.items()):
        print(f"  {t}: {n}")

    if not args.dry_run:
        GT_FLAT_DIR.mkdir(parents=True, exist_ok=True)
        draft_path = GT_FLAT_DIR / f"{args.pdf}.draft.json"
        assert_safe_output_path(draft_path)
        draft_path.write_text(json.dumps(draft, indent=2))
        print(f"\nDraft written: {draft_path.relative_to(ROOT)}")
        print(f"\nNext steps:")
        print(f"  1. Render overlay: python scripts/render_ground_truth_overlays.py "
              f"--gt-dir benchmarks/ground_truth_flat --pdf {args.pdf}")
        print(f"  2. Hand-review draft against overlay")
        print(f"  3. Mark each field '_reviewer_status: kept' or 'adjusted' or delete")
        print(f"  4. Promote: python scripts/extract_flat_pdf_ground_truth.py "
              f"--pdf {args.pdf} --promote")


if __name__ == "__main__":
    main()
